Update first-party Pulumi dependencies (#3927)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [@pulumi/kubernetes](https://pulumi.com)
([source](https://redirect.github.com/pulumi/pulumi-kubernetes)) |
dependencies | minor | [`4.23.0` ->
`4.24.0`](https://renovatebot.com/diffs/npm/@pulumi%2fkubernetes/4.23.0/4.24.0)
|
|
[github.com/pulumi/pulumi-kubernetes/sdk/v4](https://redirect.github.com/pulumi/pulumi-kubernetes)
| require | minor | `v4.23.0` -> `v4.24.0` |
|
[github.com/pulumi/pulumi/pkg/v3](https://redirect.github.com/pulumi/pulumi)
| require | minor | `v3.205.0` -> `v3.206.0` |
| [pulumi/actions](https://redirect.github.com/pulumi/actions) | action
| patch | `v6.6.0` -> `v6.6.1` |

---

### Release Notes

<details>
<summary>pulumi/pulumi-kubernetes (@&#8203;pulumi/kubernetes)</summary>

###
[`v4.24.0`](https://redirect.github.com/pulumi/pulumi-kubernetes/releases/tag/v4.24.0)

[Compare
Source](https://redirect.github.com/pulumi/pulumi-kubernetes/compare/v4.23.0...v4.24.0)

##### Added

- Added a `plainHttp` option to the `v4.Chart` resource.
([https://github.com/pulumi/pulumi-kubernetes/issues/3250](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3250))

##### Changed

-   The `pulumi.com/waitFor` annotation now uses an
[RFC9535](https://www.rfc-editor.org/rfc/rfc9535.html)-compliant
JSONPath
    parser. This makes it possible to wait for more complex scenarios.

    For example:

- To wait for a Pod's `status.phase` to be "Running" or "Succeeded":

`pulumi.com/waitFor: "jsonpath={.status[?@&#8203; == 'Running' ||
@&#8203; == 'Succeeded' ]}"`

- To wait for for an object to have a "Failed" *or* "Complete" condition
with
        a "True" value:

`pulumi.com/waitFor:
"jsonpath={.conditions[?(@&#8203;.type=='Failed'||@&#8203;.type=='Complete')].status}=True`

(Tools like [jsonpath.com](https://jsonpath.com) are very helpful for
    ensuring your JSONPath expression works as expected.)

Importantly, please note that `kubectl wait --for=jsonpath=...` supports
only
a *subset* of RFC9535. This means some complex `waitFor` annotations
will not
    be reproducible with `kubectl`.

Existing expressions should continue to work normally with one notable
exception: a selector like `.items[]` now requires an explicit wildcard,
i.e.
    `.items[*]`.

As a reminder, the `pulumi.com/waitFor` annotation is experimental and
subject to change. Similarly, RFC9535 is still only *proposed* and may
also
    change in the future.

-   `enableConfigMapMutable` and `enableSecretMutable` are now stable.

[https://github.com/pulumi/pulumi-kubernetes/pull/3886](https://redirect.github.com/pulumi/pulumi-kubernetes/pull/3886)3886)

##### Fixed

- Helm resources all now use the correct `registry/config.json` file for
credentials. For backward-compatibility `registry.json` is preferred if
it
exist[https://github.com/pulumi/pulumi-kubernetes/issues/3606](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3606)3606)

- Fixed an issue where deletions could take longer than necessary.
([https://github.com/pulumi/pulumi-kubernetes/issues/3317](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3317))

- Significantly reduced memory usage.
([https://github.com/pulumi/pulumi-kubernetes/issues/3713](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3713))

- Fixed incorrect deprecation warnings for VolumeAttributesClass.
([https://github.com/pulumi/pulumi-kubernetes/issues/3772](https://redirect.github.com/pulumi/pulumi-kubernetes/issues/3772))

-   SecretPatch inputs are now automatically marked as secret.

</details>

<details>
<summary>pulumi/pulumi (github.com/pulumi/pulumi/pkg/v3)</summary>

###
[`v3.206.0`](https://redirect.github.com/pulumi/pulumi/releases/tag/v3.206.0)

[Compare
Source](https://redirect.github.com/pulumi/pulumi/compare/v3.205.0...v3.206.0)

#### 3.206.0 (2025-11-05)

##### Features

- \[protobuf] Pass a `preview` flag to invokes so they can tell if
they're being called during a preview
[#&#8203;20827](https://redirect.github.com/pulumi/pulumi/pull/20827)

- \[cli/about] Include PULUMI_\* environment variables in the `pulumi
about` output
[#&#8203;20855](https://redirect.github.com/pulumi/pulumi/pull/20855)

- \[auto/go] Get event log over gRPC instead of trying to read it from a
text file
[#&#8203;20822](https://redirect.github.com/pulumi/pulumi/pull/20822)

- \[auto/nodejs] Get event log over gRPC instead of trying to read it
from a text file
[#&#8203;20824](https://redirect.github.com/pulumi/pulumi/pull/20824)

- \[auto/python] Get event log over gRPC instead of trying to read it
from a text file
[#&#8203;20833](https://redirect.github.com/pulumi/pulumi/pull/20833)

- \[cli/engine] Add environment variable to add --refresh to
preview,update,destroy
[#&#8203;20797](https://redirect.github.com/pulumi/pulumi/pull/20797)

- \[sdk/nodejs] Add PULUMI_NODEJS_SKIP_COMPONENT_INPUTS environment
variable to skip the new feature of sending component inputs to the
engine for diffing and state storage
[#&#8203;20842](https://redirect.github.com/pulumi/pulumi/pull/20842)

##### Bug Fixes

- \[engine] Fix duplicate resource snapshot integrity issue, when
running `pulumi up --refresh --run-program` and when a resource
`PendingReplacement` exists in the snapshot
[#&#8203;20812](https://redirect.github.com/pulumi/pulumi/pull/20812)

- \[engine] Support floating point NaN and Inf values in resource state
[#&#8203;20843](https://redirect.github.com/pulumi/pulumi/pull/20843)

##### Miscellaneous

-   \[sdk/go] Use Language.Link to link Go packages
[#&#8203;20811](https://redirect.github.com/pulumi/pulumi/pull/20811)

</details>

<details>
<summary>pulumi/actions (pulumi/actions)</summary>

###
[`v6.6.1`](https://redirect.github.com/pulumi/actions/releases/tag/v6.6.1)

[Compare
Source](https://redirect.github.com/pulumi/actions/compare/v6.6.0...v6.6.1)

##### What's Changed

- upgrade pulumi/pulumi to latest by
[@&#8203;tgummerer](https://redirect.github.com/tgummerer) in
[https://github.com/pulumi/actions/pull/1394](https://redirect.github.com/pulumi/actions/pull/1394)
- Prepare changelog for 6.6.1 by
[@&#8203;tgummerer](https://redirect.github.com/tgummerer) in
[https://github.com/pulumi/actions/pull/1395](https://redirect.github.com/pulumi/actions/pull/1395)

**Full Changelog**:
https://github.com/pulumi/actions/compare/v6...v6.6.1

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - Monday through Friday ( * * * * 1-5 ) (UTC).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNjQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFzdGVyIiwibGFiZWxzIjpbImRlcGVuZGVuY2llcyIsImltcGFjdC9uby1jaGFuZ2Vsb2ctcmVxdWlyZWQiXX0=-->

---------

Co-authored-by: pulumi-renovate[bot] <189166143+pulumi-renovate[bot]@users.noreply.github.com>
Co-authored-by: Thomas Gummerer <t.gummerer@gmail.com>