Fix lint and upgrade workflows (#4145)
Fixes this error by simplify the `make` target to not depend on bash
features.

```
Run make lint
/bin/sh: 2: pushd: not found
Error: can't load config: can't read viper config: open ../.golangci.yml: no such file or directory
Failed executing command with error: can't load config: can't read viper config: open ../.golangci.yml: no such file or directory
/bin/sh: 2: popd: not found
make: *** [Makefile:110: lint] Error 127
```

Also updates workflows and fixes remaining lint errors.

Fixes #4138.

<!--Thanks for your contribution. See [CONTRIBUTING](CONTRIBUTING.md)
    for Pulumi's contribution guidelines.

    Help us merge your changes more quickly by adding more details such
    as labels, milestones, and reviewers.-->

### Proposed changes

<!--Give us a brief description of what you've done and what it solves.
-->

### Related issues (optional)

<!--Refer to related PRs or issues: #1234, or 'Fixes #1234' or 'Closes
#1234'.
Or link to full URLs to issues or pull requests in other GitHub
repositories. -->

---------

Co-authored-by: guineveresaenger <guinevere@pulumi.com>