Fix lint and upgrade workflows
Fixes this error by simplify the `make` target to not depend on bash
features.

```
Run make lint
/bin/sh: 2: pushd: not found
Error: can't load config: can't read viper config: open ../.golangci.yml: no such file or directory
Failed executing command with error: can't load config: can't read viper config: open ../.golangci.yml: no such file or directory
/bin/sh: 2: popd: not found
make: *** [Makefile:110: lint] Error 127
```

Also updates workflows and fixes remaining lint errors.

Fixes #4138.